/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FlowService } from "../flow.service";
import { FlowCreateInput } from "./FlowCreateInput";
import { Flow } from "./Flow";
import { FlowFindManyArgs } from "./FlowFindManyArgs";
import { FlowWhereUniqueInput } from "./FlowWhereUniqueInput";
import { FlowUpdateInput } from "./FlowUpdateInput";
import { NodeFindManyArgs } from "../../node/base/NodeFindManyArgs";
import { Node } from "../../node/base/Node";
import { NodeWhereUniqueInput } from "../../node/base/NodeWhereUniqueInput";

export class FlowControllerBase {
  constructor(protected readonly service: FlowService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Flow })
  async createFlow(@common.Body() data: FlowCreateInput): Promise<Flow> {
    return await this.service.createFlow({
      data: {
        ...data,

        bot: data.bot
          ? {
              connect: data.bot,
            }
          : undefined,
      },
      select: {
        bot: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Flow] })
  @ApiNestedQuery(FlowFindManyArgs)
  async flows(@common.Req() request: Request): Promise<Flow[]> {
    const args = plainToClass(FlowFindManyArgs, request.query);
    return this.service.flows({
      ...args,
      select: {
        bot: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Flow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async flow(
    @common.Param() params: FlowWhereUniqueInput
  ): Promise<Flow | null> {
    const result = await this.service.flow({
      where: params,
      select: {
        bot: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Flow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFlow(
    @common.Param() params: FlowWhereUniqueInput,
    @common.Body() data: FlowUpdateInput
  ): Promise<Flow | null> {
    try {
      return await this.service.updateFlow({
        where: params,
        data: {
          ...data,

          bot: data.bot
            ? {
                connect: data.bot,
              }
            : undefined,
        },
        select: {
          bot: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Flow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFlow(
    @common.Param() params: FlowWhereUniqueInput
  ): Promise<Flow | null> {
    try {
      return await this.service.deleteFlow({
        where: params,
        select: {
          bot: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/nodes")
  @ApiNestedQuery(NodeFindManyArgs)
  async findNodes(
    @common.Req() request: Request,
    @common.Param() params: FlowWhereUniqueInput
  ): Promise<Node[]> {
    const query = plainToClass(NodeFindManyArgs, request.query);
    const results = await this.service.findNodes(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,

        edge: {
          select: {
            id: true,
          },
        },

        flow: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/nodes")
  async connectNodes(
    @common.Param() params: FlowWhereUniqueInput,
    @common.Body() body: NodeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nodes: {
        connect: body,
      },
    };
    await this.service.updateFlow({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/nodes")
  async updateNodes(
    @common.Param() params: FlowWhereUniqueInput,
    @common.Body() body: NodeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nodes: {
        set: body,
      },
    };
    await this.service.updateFlow({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/nodes")
  async disconnectNodes(
    @common.Param() params: FlowWhereUniqueInput,
    @common.Body() body: NodeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nodes: {
        disconnect: body,
      },
    };
    await this.service.updateFlow({
      where: params,
      data,
      select: { id: true },
    });
  }
}
